### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by Alagyira** [ReactNativeSchool/react-native-quiz#4] opened 2020-05-11 00:19 UTC
Please I keep getting this if i attempt to run "
Failed to compile.
C:/Users/MEDIA BENNY/Desktop/react-native-quiz-master/node_modules/expo/build/launch/registerRootComponent.web.js
Module not found: Can't resolve 'react-native-web/dist/exports/AppRegistry' in 'C:\Users\MEDIA BENNY\Desktop\react-native-quiz-master\node_modules\expo\build\launch''

Can you please help me fix the issue

**Comment by spencercarli** [comment] 2020-05-13 16:03
Have you run `npm install`/`yarn install` after downloading?

**Comment by Alagyira** [comment] 2020-05-15 18:54
> 
> 
> Have you run `npm install`/`yarn install` after downloading?

Yes I did

**Comment by radoslav-d** [comment] 2020-05-19 15:15
Hello there,
I was looking at this app, which looks interesting for React Native beginners and I came across the same problem.

**Comment by spencercarli** [comment] 2020-05-19 16:42
@radoslav-d are you also on windows? I can't reproduce this error on MacOS.

**Comment by spencercarli** [comment] 2020-05-19 16:44
Are you trying to run the app via `yarn run android`?

**Comment by spencercarli** [comment] 2020-05-19 16:48
Can you also try running `yarn add expo@latest` and then trying `yarn run android` again? I'm not sure where this issue is coming from. Seems to be Windows specific.

**Comment by radoslav-d** [comment] 2020-05-20 06:59
> Can you also try running `yarn add expo@latest` and then trying `yarn run android` again? I'm not sure where this issue is coming from. Seems to be Windows specific.

I am on MacOS and I am doing the following:
`npm install`
`npm run ios`
then in the interactive console, I type `w` to run in web, which results in this error.
If I do it with yarn, the error still appears.
It think it is related to the web option.
@spencercarli Can you try running in in the web to see if you can reproduce the error?

**Comment by spencercarli** [comment] 2020-05-20 14:45
Ok, thanks for letting me know.

This project is for an example in a mobile development course and I have no intention to support web at this time. You should be able to add web support following [these instructions](https://docs.expo.io/guides/running-in-the-browser/).

I'm going to close this issue since it's not something I'll be supporting.

**Closed by spencercarli** 2020-05-20 14:45 UTC
